[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "imgdata-core"
version = "0.0.1"
description = "Core data structures and interfaces for image parsing."
authors = [{name="chqy99", email="you@example.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["core", "core.*"]
